### ISSUE TITLE
primrose installation clarification

### ISSUE THREAD

**Issue by parul-l** [ww-tech/primrose#17]
Ensuring that `graphviz` is installed before `pip` installing `primrose`. Perhaps I just misinterpreted the docs.

**Comment by parul-l** [comment]
Also had to `pip install pygraphviz`

**Comment by briangrahamww** [comment]
maybe make optional install for pygraphviz
e.g. be able to use
`pip install primrose[pygraphviz] or something similar`

**Comment by briangrahamww** [comment]
or cache error when trying to import

**Comment by briangrahamww** [comment]
Closed by PR #27
