### ISSUE TITLE
Use YAML, not JSON

### ISSUE THREAD

**Issue by impredicative** [ww-tech/primrose#18]
Please consider using YAML, not JSON for user written config files. JSON is better for machine written files. YAML also natively supports comments. If YAML is good enough for k8s, it's probably good enough for this project. Thanks.

**Comment by mskarlinski-ww** [comment]
Hey @impredicative, we have full support for YAML configuration files. Some of our examples are still written in JSON is all. Check out the documentation here: https://github.com/ww-tech/primrose/blob/master/README_DAG_CONFIG.md

**Comment by impredicative** [comment]
I encourage emphasizing YAML in the docs and examples, and deemphasizing JSON.
