### ISSUE TITLE
Add git tag for each PyPI release

### ISSUE THREAD

**Issue by impredicative** [ww-tech/primrose#20]
As a good general practice, for each PyPI release, the associated commit in the git repo ought to have a tag representing the version. For example, the git commit corresponding to the 1.0.6 version on PyPI could have a git tag named `v1.0.6` or even just `1.0.6`. These can also be backfilled. For future release, the PyPI release could be triggered by a matching tag push via an automated CI CD pipeline, perhaps using GitHub Actions. Thanks.

**Comment by briangrahamww** [comment]
See Open PR #26
