### ISSUE TITLE
removed

### ISSUE THREAD

**Issue by yamengzhang** [ww-tech/primrose#61]

**Comment by kzecchini** [comment]
I think this description might need a little work (it is close!). If we do `bash scripts/get_trigger_env.sh <job identifier>`, we only get idb configuration. What we want is to add into that script the `env` field for jobs/deployments as well.

If we do `tcli job show datasciencejobs/churn-model/prod/us-east4.gcp` we should be able to see the `env`. We need to parse the output from this in the bash script and append to the idb configuration.

**Comment by yamengzhang** [comment]
@kzecchini Ah just noticed that I put the wrong command! Thank you!
