### ISSUE TITLE
specific exception handling

### ISSUE THREAD

**Issue by kzecchini** [ww-tech/primrose#8]
Most of the exceptions thrown in the code are generic errors of class `Exception`. It would be great to specify exactly the kind of exception being thrown, perhaps creating an exception module. This would make it easier to catch `primrose` specific exceptions if necessary. An example from `primrose.data_object.DataObject.get`:
```
if rtype not in DataObjectResponseType.values():
            raise Exception("Unrecognized rtype: %s" % rtype)

if not instance_name in self.data_dict.keys():
            raise Exception("Key not found: %s" % instance_name)
```
If we are just using built in exceptions, I think the first should probably be a `ValueError`, the second a `KeyError`. Alternatively, creating exceptions with a `PrimroseError` base is also an option.

**Comment by briangrahamww** [comment]
Noting that we should first create a specific primrose base exception class that includes information about the node where the error occured
